import React from 'react';
import { Badge } from '@/components/ui/badge';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { CheckCircle, AlertCircle, Info, Zap } from 'lucide-react';

interface ConfidenceBadgeProps {
  confidence: 'high' | 'medium' | 'low' | 'ai-generated';
  showTooltip?: boolean;
  size?: 'default' | 'sm';
  variant?: 'default' | 'outline' | 'secondary';
}

export const ConfidenceBadge: React.FC<ConfidenceBadgeProps> = ({
  confidence,
  showTooltip = true,
  size = 'default',
  variant = 'outline'
}) => {
  const getConfidenceConfig = (conf: string) => {
    switch (conf) {
      case 'high':
        return {
          label: 'High Confidence',
          color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
          icon: <CheckCircle className="h-3 w-3" />,
          description: 'AI is highly confident in this assessment based on strong data patterns and regulatory guidance.'
        };
      case 'medium':
        return {
          label: 'Medium Confidence',
          color: 'bg-amber-100 text-amber-800 border-amber-200',
          icon: <AlertCircle className="h-3 w-3" />,
          description: 'AI has moderate confidence. Review recommended to ensure accuracy.'
        };
      case 'low':
        return {
          label: 'Low Confidence',
          color: 'bg-slate-100 text-slate-800 border-slate-200',
          icon: <Info className="h-3 w-3" />,
          description: 'AI has limited confidence. Manual review and validation strongly recommended.'
        };
      case 'ai-generated':
        return {
          label: 'AI Generated',
          color: 'bg-violet-100 text-violet-800 border-violet-200',
          icon: <Zap className="h-3 w-3" />,
          description: 'This content was generated by AI. Please review and modify as needed.'
        };
      default:
        return {
          label: 'Unknown',
          color: 'bg-slate-100 text-slate-800 border-slate-200',
          icon: <Info className="h-3 w-3" />,
          description: 'Confidence level unknown.'
        };
    }
  };

  const config = getConfidenceConfig(confidence);

  const badge = (
    <Badge 
      variant={variant}
      className={`${config.color} ${size === 'sm' ? 'text-xs px-2 py-0.5' : 'text-sm'} font-medium`}
    >
      <span className="flex items-center gap-1">
        {config.icon}
        {config.label}
      </span>
    </Badge>
  );

  if (!showTooltip) {
    return badge;
  }

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          {badge}
        </TooltipTrigger>
        <TooltipContent>
          <p className="max-w-xs text-sm">{config.description}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
};