// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tovpvjztahjquncdqwuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvdnB2anp0YWhqcXVuY2Rxd3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjU4ODQsImV4cCI6MjA3NDE0MTg4NH0._kH2zT5h_RWb-N-BSqhI_yzUReO3VQuNoHIpLQmuZGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});